contact_links:
  - name: ğŸ“« Feature Request 
    url: https://github.com/tjarbo/discord-moodle-bot/discussions/categories/ideas
    about: You have an amazing idea? Tell us about in our Discussions Channel 
  - name: â“ Question
    url: https://github.com/tjarbo/discord-moodle-bot/discussions/categories/q-a
    about: Ask your question in our Discussions Channel